modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Infinite-Coal/issues/new/choose"
[[mods]]
modId="infcoal"
version="${file.jarVersion}"
displayName="Infinite Coal"
displayURL="https://www.curseforge.com/minecraft/mc-mods/infinite-coal"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds one Item: Infinite Coal"

[[dependencies.infcoal]]
modId="forge"
mandatory=true
versionRange="[38.0.14,)"
ordering="NONE"
side="BOTH"

[[dependencies.infcoal]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"